### ISSUE TITLE
sentry.exceptions.InvalidConfiguration: 'unix_socket_path'

### ISSUE THREAD

**Issue by agb80** [getsentry/rb#13]
I'm upgrading from an on premise sentry 7.6 installation and blocked by this error. I made a patch similar to this: https://github.com/getsentry/sentry/pull/2322, changing 'path' with 'unix_socket_path' on sentry but trough above exception.

I cannot change the redis server because is being in used for another app so, could you please guide me on how can I implement this change? Thanks in advance!

**Comment by mitsuhiko** [comment]
Closing this here as rb itself is perfectly capable of connecting to unix sockets. I will update the other issue with thoughts on the problem.
